### ISSUE TITLE
docker image ships with log4j 2.14.1

### ISSUE THREAD

**Issue by luspi** [lamarios/SpendSpentSpent#15]
My understanding of java is rather limited and I'm unable to say that this really poses an issue for SpendSpentSpent, but it seems like the docker image ships log4j in version 2.14.1. Given the recently disclosed security issue with that version (and also with version 2.15), it probably should be updated to version 2.16.0.

**Comment by lamarios** [comment]
Hi, thanks for the concern :) 

This project shouldn't be affected as it's based on spring boot (since early this year), read this: https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot

Earlier version of the application might have been impacted but I don't recall exactly  how it was set up before. So if you're using this software please make sure to use the latest version of the image.
